### ISSUE TITLE
strict_min_version

### ISSUE THREAD

**Issue by grahamperrin** [willdurand/amo-info#3]
1.3.0 

> Works with Firefox 42.0 and later

– but presents no icon in (e.g.) Waterfox 56.2.7.1 so you might want to set a strict minimum. I'm not seeking compatibility with Waterfox :)

Cheers

**Comment by grahamperrin** [comment]
https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#Firefox_(Gecko)_properties

**Comment by willdurand** [comment]
ah yep, thanks. would you like to contribute maybe?

**Comment by grahamperrin** [comment]
Thanks, and sorry I didn't contribute … I so rarely do PRs, I half-lost the know-how (haven't had the head space, recently, to regain it). I know, PRs aren't complicated :) but I just haven't had the head space!

----

Way off-topic, are you aware of any extension (or other approach) that might allow an end user of YouTube to determine whether they're subject to A/B testing?

**Comment by willdurand** [comment]
> Way off-topic, are you aware of any extension (or other approach) that might allow an end user of YouTube to determine whether they're subject to A/B testing?

I don't, sorry :(
