### ISSUE TITLE
Run the extension for localhost

### ISSUE THREAD

**Issue by kumar303** [willdurand/amo-info#33]
Would it be possible to run the extension for localhost? It would be convenient. For cases where you aren't running the AMO server on localhost then the extension wouldn't work but that seems fine.

**Comment by willdurand** [comment]
What would you like to have? The extension gets enabled based on a list of domains. I guess `localhost:3000` is pretty generic but I see no reason not to enable it. What would be your use case?

**Comment by kumar303** [comment]
Yeah, I wanted it to run on `localhost:3000` for my use case. I was reviewing a patch and I wasn't sure if my local config was enabling the right flag or not so this extension would have made it a bit easier to check.

**Comment by eviljeff** [comment]
can we have the default addons-server host too, `olympia.test`?

**Comment by willdurand** [comment]
fixed by https://github.com/willdurand/amo-info/commit/67c97af8521c34002dbd0f09e52e48a37d904eb0

**Comment by willdurand** [comment]
I released version `1.10`, see: https://addons.mozilla.org/en-US/firefox/addon/amo-info/
